// <auto-generated />
namespace RJ.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TP_ANNOTAIONS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TP_ANNOTAIONS));
        
        string IMigrationMetadata.Id
        {
            get { return "202203061946525_TP_ANNOTAIONS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
